### ISSUE TITLE
slice bounds out of range, title.go:49

### ISSUE THREAD

**Issue by aaaton** [jdkato/prose#18]
I'm trying to use `TItleConverter.Title()`, but it panics on me, when the string contains certain multibyte characters.

Crashing testcases:

```golang
        type tc struct {
		name  string
		input string
		want  string
	}
	tests := []tc{
                tc{"panic", "This Agreement, dated [DATE] (the “Effective Date”) for Design Services (the “Agreement”) is between [DESIGNER NAME], of [DESIGNER COMPANY](“Designer”), and [CLIENT NAME], of [CLIENT COMPANY] (“Client”) (together known as the “Parties”), for the performance of said Design Services and the production of Deliverables, as described in Schedule A, attached hereto and incorporated herein by reference.", "panic"},
		tc{"panic", "Crash,”“us,” “our” or “we” means Crash Network, Inc. (d/b/a Crash) and its subsidiaries and affiliates.", "panic"},
		tc{"panic", "a “[“New Entity”],” an [Institution] and [Institution].", "panic"},
        }
```

**Comment by jdkato** [comment]
Thanks for the report.

The panic was due to a `len` call (instead of `utf8.RuneCountInString`). I've added passing test cases for your first and third examples on the `fix/title` branch:

https://github.com/jdkato/prose/blob/04b8c53be5dc91f40c711452e3b272851ef762d4/testdata/title.json#L254-L261

The second example seems to be bit more tricky, though. Here are a few tests I ran:

1. prose: "“Crash,”“us,” “**Our**” or “**We**” Means Crash Network, Inc. (D/B/**a** Crash) and Its Subsidiaries and Affiliates."
2. Python's [titlecase](https://pypi.python.org/pypi/titlecase) library: '“Crash,”“us,” “our” or “we” Means Crash Network, Inc. (D/B/**a** Crash) and Its Subsidiaries and Affiliates.'
3. [titlecase.com](http://titlecase.com/): '“**crash**,”“us,” “our” or “we” Means Crash Network, Inc. (D/B/A Crash) and Its Subsidiaries and Affiliates.'

The bolded words seem to be handled incorrectly.

**Comment by aaaton** [comment]
Very nice! So it doesn't panic anymore? 
I can see the TCs being a bit tricky, since there is a lot of punctuation going on, but in my opinion the output of prose looks good.

**Comment by jdkato** [comment]
Correct -- the panic should be fixed. I haven't pushed the changes to master yet, though (I'll do that soon).

**Comment by jdkato** [comment]
Merged. Let me know if you run into any other issues.
