### ISSUE TITLE
Improve syllable counting

### ISSUE THREAD

**Issue by jdkato** [jdkato/prose#4]
This looks like a promising implementation: https://github.com/wooorm/syllable

**Comment by elliott5** [comment]
I presume you have seen the Go port at: https://github.com/mtso/syllables

**Comment by jdkato** [comment]
I actually wasn't aware of that&mdash;thanks for letting me know!

I forked the project and added `wooorm/syllable`'s test suite of [4384 words](https://github.com/jdkato/syllables/blob/master/testdata/syllables.json). Initially, `mtso/syllables` had 104 failing cases. After a [few minor changes](https://github.com/jdkato/syllables/commits/master), I got that down to a single case. 

Performance-wise, though, it's not great:

```
BenchmarkSyllables-4                   3         345044683 ns/op
```

I'll see if I can clean my fork up more, and then I'll submit a PR.

**Comment by elliott5** [comment]
I'd put money on the speed issue being because the ```*Regexp``` methods ```ReplaceAllString()``` and ```ReplaceAllStringFunc()``` cast from string->[]byte, to their stuff, then cast from []byte->string again every time they are called. 
The ```syllables.In()``` function contains 10 of these calls, so there is a lot of memory copying and garbage collection happening for no benefit.
It would be faster to make ```syllables.InBytes()``` contain the logic and do it all using []byte rather than string types by calling ```*Regexp``` methods ```ReplaceAll()``` and ```ReplaceAllFunc()```.
As it is always fun to speed things up, I was tempted to fork the code and do it myself ... but I thought it would be rather selfish to deny you the pleasure.

**Comment by jdkato** [comment]
Yep, it looks like that's the case. I've rewritten about [half of the library](https://github.com/jdkato/prose/blob/master/summarize/syllables.go) to rely less on regular expressions (notably, I've removed all `ReplaceAllStringFunc` calls and reduced the overall `regexp` use to 7 calls) and here's the results so far:

```
name         old time/op  new time/op  delta
Syllables-4   135ms ± 5%    99ms ± 5%  -26.70%  (p=0.016 n=4+5)
```

This still has room for improvement, as I'm calling `FindAllString` 7 times.

**Comment by elliott5** [comment]
Good work so far!

**Comment by mtso** [comment]
Looks great so far~

I'm a Go beginner myself and just used this to preprocess html files, so I haven't really looked at performance so far.
The `.InBytes()` func was an afterthought, actually, so elliot5 makes a good point that it could probably contain the logic instead.

**Comment by jdkato** [comment]
I'm going to consider this closed for now: the performance is the same as above (~99 ms/op) and on a test suite of 9462 words it got 8798 correct (~93%). `wooorm/syllable` scored 8797.
